### ISSUE TITLE
Support Pod SecurityPolicy?

### ISSUE THREAD

**Issue by changhyuni** [DataDog/managed-kubernetes-auditing-toolkit#10]
I was so happy to see you support "irsa" Do you have any plans to support "pod security policy" as well?

**Comment by christophetd** [comment]
Thanks for the question! What would be your use-case exactly? (Also note that Pod security policy is deprecated in recent version of Kubernetes)

**Comment by changhyuni** [comment]
@christophetd 
I want to pull out a list of Pod Security Policies with labels

**Comment by christophetd** [comment]
Pod security policy isn't something that's specific to managed Kubernetes environments, so likely not a good fit for MKAT. Thanks for suggesting!
